---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - remediation.kubemedic.io
  resources:
  - selfremediationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - remediation.kubemedic.io
  resources:
  - selfremediationpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - remediation.kubemedic.io
  resources:
  - selfremediationpolicies/status
  verbs:
  - get
  - patch
  - update
