# KubeMedic Configuration Values

# Namespace configuration
namespace: kubemedic

# Controller configuration
controller:
  # Number of controller replicas
  replicas: 1
  
  # Container image configuration
  image:
    repository: ikepcampbell/kubemedic-controller
    tag: latest
    pullPolicy: IfNotPresent
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Log level (debug, info, warn, error)
  logLevel: "info"

# Certificate Management Configuration
certificates:
  # Use cert-manager for automatic certificate management (recommended)
  useCertManager: true
  
  # Custom certificate configuration (only used if useCertManager: false)
  custom:
    # Base64 encoded certificates (required if useCertManager: false)
    tlsCert: ""
    tlsKey: ""
    caCert: ""

# Webhook Configuration
webhook:
  # Image configuration
  image:
    repository: ghcr.io/ikepcampbell/kubemedic-webhook
    tag: latest
    pullPolicy: IfNotPresent
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  # Security context
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  # Service configuration
  service:
    type: ClusterIP
    port: 443
    targetPort: 8443

# Certificate Renewal Configuration
certificateRenewal:
  # Time before expiry to trigger renewal
  threshold: "7d"
  # Minimum time between renewal attempts
  cooldownPeriod: "1h"
  # Duration to wait before taking action
  checkDuration: "1m"

# Image Pull Secrets
imagePullSecrets:
  - name: ghcr-secret

# RBAC configuration
rbac:
  # Create ClusterRole and ClusterRoleBinding
  create: true
  
  # Service account name
  serviceAccountName: kubemedic-controller

# Metrics configuration
metrics:
  # Enable Prometheus metrics
  enabled: true
  
  # Port to expose metrics on
  port: 8080

# Safety limits configuration
safetyLimits:
  # Maximum scale factor for remediation
  maxScaleFactor: 2
  
  # Minimum number of pods to maintain
  minPods: 1
  
  # Maximum duration for temporary scaling
  maxScalingDuration: "2h"
  
  # Maximum number of actions per hour
  maxActionsPerHour: 5

# Integration configuration
integrations:
  # Grafana integration
  grafana:
    enabled: false
    # webhookUrl: "https://grafana.example.com/webhook" 