apiVersion: remediation.kubemedic.io/v1alpha1
kind: SelfRemediationPolicy
metadata:
  name: memory-management
  namespace: default
spec:
  rules:
    - name: high-memory-scale
      conditions:
        - type: MemoryUsage
          threshold: "90%"
          duration: "3m"
      actions:
        - type: ScaleUp
          target:
            kind: Deployment
            name: memory-intensive-app
            namespace: default
    - name: critical-memory
      conditions:
        - type: MemoryUsage
          threshold: "95%"
          duration: "1m"
      actions:
        - type: RestartPod
          target:
            kind: Pod
            name: memory-intensive-app
            namespace: default
  cooldownPeriod: "10m"
  grafanaIntegration:
    enabled: true
    webhookUrl: "https://grafana.example.com/webhook/memory-alerts" 